<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BookSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('books')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        DB::table('books')->insert([
            ['title' => 'Laskar Pelangi', 'author' => 'Andrea Hirata', 'year' => 2005, 'cover' => 'https://images.unsplash.com/photo-1661936901394-a993c79303c7?w=300&q=80', 'description' => 'Novel ini bercerita tentang sepuluh anak kampung di Belitung yang berjuang untuk mendapatkan pendidikan di sekolah Muhammadiyah yang hampir roboh. Dengan segala keterbatasan, mereka membuktikan bahwa mimpi tidak mengenal batas kemiskinan. Kisah persahabatan, perjuangan, dan semangat yang mengharukan hati.', 'status' => 'Tersedia', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'Sang Pemimpi', 'author' => 'Andrea Hirata', 'year' => 2006, 'cover' => 'https://images.unsplash.com/photo-1765282946949-03ec841313ca?w=300&q=80', 'description' => 'Sekuel Laskar Pelangi yang mengisahkan Ikal dan sahabatnya Arai yang bermimpi untuk bersekolah di Prancis. Mereka bekerja keras sebagai kuli di pelabuhan Belitung demi mewujudkan mimpi besar mereka mengelilingi Eropa.', 'status' => 'Tersedia', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'Edensor', 'author' => 'Andrea Hirata', 'year' => 2007, 'cover' => 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=300&q=80', 'description' => 'Ikal dan Arai akhirnya berhasil berkuliah di Universite de Paris, Sorbonne. Petualangan mereka menjelajahi Eropa menjadi kisah yang penuh warna, dari perjalanan dengan sepeda motor butut hingga menemukan makna hidup di desa kecil bernama Edensor.', 'status' => 'Tersedia', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'Maryamah Karpov', 'author' => 'Andrea Hirata', 'year' => 2008, 'cover' => 'https://images.unsplash.com/photo-1524985069026-dd778a71c7b4?w=300&q=80', 'description' => 'Novel penutup tetralogi Laskar Pelangi. Ikal kembali ke Belitung dan berjuang untuk menemukan cinta sejatinya, A Ling. Ia membangun kapal sendiri untuk menyeberangi lautan demi menemukannya di antara pulau-pulau terpencil.', 'status' => 'Dipinjam', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'Bumi Manusia', 'author' => 'Pramoedya Ananta Toer', 'year' => 1980, 'cover' => 'https://images.unsplash.com/photo-1775276406338-3dc8e6949372?w=300&q=80', 'description' => 'Novel pertama dari Tetralogi Buru karya Pramoedya. Mengisahkan Minke, pemuda pribumi terpelajar di era kolonial Belanda yang jatuh cinta pada Annelies, gadis Indo cantik. Sebuah kisah tentang cinta, kemanusiaan, dan perjuangan melawan penindasan kolonialisme.', 'status' => 'Tersedia', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'Anak Semua Bangsa', 'author' => 'Pramoedya Ananta Toer', 'year' => 1980, 'cover' => 'https://images.unsplash.com/photo-1541963463532-d68292c34b19?w=300&q=80', 'description' => 'Kelanjutan Bumi Manusia. Minke mulai menyadari kondisi bangsanya yang tertindas. Ia belajar dari berbagai kisah perjuangan di seluruh dunia dan mulai menggunakan pena sebagai senjata melawan ketidakadilan kolonial.', 'status' => 'Tersedia', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'Jejak Langkah', 'author' => 'Pramoedya Ananta Toer', 'year' => 1985, 'cover' => 'https://images.unsplash.com/photo-1495640452828-3df6795cf69b?w=300&q=80', 'description' => 'Minke kini aktif dalam gerakan pergerakan nasional. Ia mendirikan organisasi dan surat kabar untuk membela hak-hak pribumi. Novel ini menggambarkan kebangkitan kesadaran nasional Indonesia di awal abad ke-20.', 'status' => 'Dipinjam', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'Negeri 5 Menara', 'author' => 'Ahmad Fuadi', 'year' => 2009, 'cover' => 'https://images.unsplash.com/photo-1758875630351-b65d256e4dfe?w=300&q=80', 'description' => 'Kisah Alif Fikri yang meninggalkan kampung halamannya di Maninjau untuk bersekolah di Pondok Madani. Bersama lima sahabatnya dari berbagai penjuru Indonesia, mereka bermimpi meraih cita-cita setinggi langit dengan mantra "Man Jadda Wajada".', 'status' => 'Tersedia', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'Ranah 3 Warna', 'author' => 'Ahmad Fuadi', 'year' => 2011, 'cover' => 'https://images.unsplash.com/photo-1476275466078-4cdc8b93cd43?w=300&q=80', 'description' => 'Alif melanjutkan perjuangannya di Bandung dan kemudian ke Amerika Serikat. Dengan beasiswa dan kerja keras, ia membuktikan bahwa anak pesantren pun bisa bersaing di panggung internasional.', 'status' => 'Tersedia', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'Perahu Kertas', 'author' => 'Dee Lestari', 'year' => 2009, 'cover' => 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=300&q=80', 'description' => 'Kugy dan Keenan, dua jiwa yang saling melengkapi namun terpisahkan oleh keadaan. Kugy si pencerita dengan dunia dongengnya, dan Keenan si pelukis berbakat. Kisah cinta yang puitis dan mengalir seperti perahu kertas di sungai kenangan.', 'status' => 'Tersedia', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'Supernova: Ksatria, Putri & Bintang Jatuh', 'author' => 'Dee Lestari', 'year' => 2001, 'cover' => 'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=300&q=80', 'description' => 'Dua orang mahasiswa, Reuben dan Dhimas, menulis sebuah novel tentang Ksatria dan Putri. Kisah fiksi mereka terjalin dengan kehidupan nyata Ferre dan Rana dengan cara yang mengejutkan. Novel pertama Supernova yang memadukan sains, spiritualitas, dan cinta.', 'status' => 'Tersedia', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'Pulang', 'author' => 'Leila S. Chudori', 'year' => 2012, 'cover' => 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=300&q=80', 'description' => 'Dimas Suryo, seorang eksil politik Indonesia di Paris, tidak pernah bisa pulang ke tanah airnya setelah peristiwa 1965. Novel ini mengisahkan kerinduan, pengkhianatan, dan perjuangan identitas yang melintasi tiga generasi dan dua benua.', 'status' => 'Tersedia', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'Laut Bercerita', 'author' => 'Leila S. Chudori', 'year' => 2017, 'cover' => 'https://images.unsplash.com/photo-1519682337058-a94d519337bc?w=300&q=80', 'description' => 'Biru Laut, seorang aktivis mahasiswa, diculik dan menghilang di era Orde Baru. Kisahnya diceritakan dari dua sudut pandang: Laut sendiri sebelum penghilangan, dan adiknya Asmara yang berjuang mencari kebenaran. Novel yang mengharukan tentang keberanian dan kehilangan.', 'status' => 'Dipinjam', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'Namaku Alam', 'author' => 'Leila S. Chudori', 'year' => 2022, 'cover' => 'https://images.unsplash.com/photo-1550399105-c4db5fb85c18?w=300&q=80', 'description' => 'Alam Suwarna, putra seorang tapol 1965, tumbuh dengan bayang-bayang stigma yang menghantui keluarganya. Novel ini mengisahkan pencarian identitas seorang anak muda di tengah luka sejarah yang belum sembuh.', 'status' => 'Tersedia', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'Hujan', 'author' => 'Tere Liye', 'year' => 2016, 'cover' => 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=300&q=80', 'description' => 'Di tahun 2042, dunia berubah drastis. Lail dan Esok bertemu saat bencana dahsyat melanda kota mereka. Kisah cinta yang tumbuh di tengah kehancuran, melewati waktu dan perpisahan, hingga pada sebuah keputusan yang akan mengubah segalanya.', 'status' => 'Tersedia', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'Bumi', 'author' => 'Tere Liye', 'year' => 2014, 'cover' => 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=300&q=80', 'description' => 'Raib, seorang gadis 15 tahun, memiliki kemampuan menghilang. Bersama dua sahabatnya, Seli dan Ali, ia menemukan bahwa ada klan-klan tersembunyi yang hidup di dunia paralel bumi. Petualangan fantasi yang seru dan penuh imajinasi.', 'status' => 'Tersedia', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'Rindu', 'author' => 'Tere Liye', 'year' => 2014, 'cover' => 'https://images.unsplash.com/photo-1491841573634-28140fc7ced7?w=300&q=80', 'description' => 'Tahun 1938, kapal uap Blitar Holland membawa ratusan jemaah haji dari Makassar menuju Mekkah. Di atas kapal ini, lima kisah tentang kerinduan, penyesalan, kebencian, dan cinta terjalin menjadi satu perjalanan spiritual yang tak terlupakan.', 'status' => 'Dipinjam', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'Rembulan Tenggelam di Wajahmu', 'author' => 'Tere Liye', 'year' => 2009, 'cover' => 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=300&q=80', 'description' => 'Ray, seorang pengusaha sukses yang keras dan kejam, menjelang ajalnya diberikan kesempatan untuk menjawab lima pertanyaan tentang hidupnya. Sebuah perjalanan waktu yang memaksanya merenungkan pilihan-pilihan hidupnya.', 'status' => 'Tersedia', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'Hafalan Shalat Delisa', 'author' => 'Tere Liye', 'year' => 2005, 'cover' => 'https://images.unsplash.com/photo-1535905557558-afc4877a26fc?w=300&q=80', 'description' => 'Delisa, bocah 6 tahun dari Aceh, sedang berjuang menghafal bacaan shalat untuk ujian sekolah ketika tsunami 2004 menghantam. Kisah yang mengharukan tentang keikhlasan, kehilangan, dan keajaiban iman seorang anak kecil.', 'status' => 'Tersedia', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'Devotion of Suspect X', 'author' => 'Keigo Higashino', 'year' => 2005, 'cover' => 'https://images.unsplash.com/photo-1587614382346-4ec70e388b28?w=300&q=80', 'description' => 'Ishigami, seorang jenius matematika, secara tidak sengaja menyaksikan tetangganya membunuh mantan suaminya. Demi melindungi wanita yang dicintainya, ia merancang alibi yang sempurna. Sebuah thriller psikologis yang mempertanyakan batas antara kejahatan dan pengorbanan.', 'status' => 'Tersedia', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'Salvation of a Saint', 'author' => 'Keigo Higashino', 'year' => 2008, 'cover' => 'https://images.unsplash.com/photo-1589998059171-988d887df646?w=300&q=80', 'description' => 'Yoshitaka ditemukan tewas keracunan kopi di rumahnya. Istrinya Ayane memiliki alibi sempurna karena sedang berada di Sapporo saat kejadian. Detektif Kusanagi dan rekannya Kaoru harus memecahkan misteri yang tampaknya mustahil ini.', 'status' => 'Dipinjam', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'Malice', 'author' => 'Keigo Higashino', 'year' => 1996, 'cover' => 'https://images.unsplash.com/photo-1491841573634-28140fc7ced7?w=300&q=80', 'description' => 'Penulis terkenal Kunihiko Hidaka ditemukan tewas di malam sebelum ia pindah ke Kanada. Sahabatnya sendiri menjadi tersangka utama. Namun motif pembunuhan ini jauh lebih gelap dan kompleks dari yang terlihat di permukaan.', 'status' => 'Tersedia', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'Journey Under the Midnight Sun', 'author' => 'Keigo Higashino', 'year' => 1999, 'cover' => 'https://images.unsplash.com/photo-1476275466078-4cdc8b93cd43?w=300&q=80', 'description' => 'Selama 19 tahun, dua anak yang terlibat dalam pembunuhan misterius tumbuh menjadi dewasa dengan identitas tersembunyi. Sebuah novel gelap tentang obsesi, kejahatan, dan rahasia yang tidak pernah bisa dikubur selamanya.', 'status' => 'Tersedia', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'Cantik Itu Luka', 'author' => 'Eka Kurniawan', 'year' => 2002, 'cover' => 'https://images.unsplash.com/photo-1524985069026-dd778a71c7b4?w=300&q=80', 'description' => 'Dewi Ayu, seorang perempuan cantik yang terpaksa menjadi pelacur di masa penjajahan Jepang, bangkit dari kuburan setelah 21 tahun. Novel magis-realis yang mengisahkan empat generasi perempuan dalam latar sejarah Indonesia yang penuh gejolak.', 'status' => 'Tersedia', 'created_at' => now(), 'updated_at' => now()],
            ['title' => 'Lelaki Harimau', 'author' => 'Eka Kurniawan', 'year' => 2004, 'cover' => 'https://images.unsplash.com/photo-1495640452828-3df6795cf69b?w=300&q=80', 'description' => 'Margio membunuh Anwar Sadat dengan cara yang mengerikan — menggigit lehernya hingga putuh. Kisah ini mengungkap lapisan demi lapisan rahasia keluarga dan dendam yang terpendam dalam balutan realisme magis yang khas Eka Kurniawan.', 'status' => 'Dipinjam', 'created_at' => now(), 'updated_at' => now()],
        ]);
    }
}